# Generated by Django 6.0.1 on 2026-01-28 12:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(help_text='Camera index (0), RTSP URL, or video file path', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('folder_path', models.CharField(max_length=500)),
                ('video_path', models.CharField(max_length=500)),
                ('excel_path', models.CharField(max_length=500)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVP.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_secret', models.CharField(blank=True, max_length=255)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('backup_codes', models.TextField(blank=True, help_text='JSON list of backup codes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_class', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('bbox_x', models.IntegerField()),
                ('bbox_y', models.IntegerField()),
                ('bbox_width', models.IntegerField()),
                ('bbox_height', models.IntegerField()),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='MVP_detecti_user_id_0ce9fe_idx'), models.Index(fields=['object_class'], name='MVP_detecti_object__164592_idx'), models.Index(fields=['session_id'], name='MVP_detecti_session_a70ab3_idx')],
            },
        ),
    ]
