# Generated by Django 6.0.1 on 2026-02-08 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlog',
            name='cam_id',
            field=models.CharField(blank=True, help_text='Camera ID or video identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='detected_items',
            field=models.JSONField(blank=True, default=list, help_text='All detected items in this frame as JSON array'),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='detection_type',
            field=models.CharField(blank=True, help_text="Type of detection: 'video' or 'live'", max_length=50),
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['cam_id'], name='MVP_detecti_cam_id_7e7165_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['detection_type'], name='MVP_detecti_detecti_f689a4_idx'),
        ),
    ]
