# Generated by Django 6.0.1 on 2026-02-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVP', '0002_add_detection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_id',
            field=models.CharField(blank=True, help_text='Camera ID e.g. CAM-01', max_length=50),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='recording_path',
            field=models.CharField(blank=True, help_text='Path to recording file when detection is from live recording', max_length=500),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='video_path',
            field=models.CharField(blank=True, help_text='Path to video file when detection is from uploaded video', max_length=500),
        ),
    ]
